
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://42.192.137.253:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: myblog
    password: Myblog@158
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: warn
    com.xujj: info
  file: log/blog-pro.lo

server:
  port: 80
